### ISSUE TITLE
Don't eat food behind snakes

### ISSUE THREAD

**Issue by ghost** [ermiyaeskandary/Slither.io-bot#103]
it really is pointless trying to eat or especially boost for food that is in or behind a snake, and it usually gets your snake killed. so if the food is behind an enemy tail it should not be considered as food.

**Comment by Drflash55** [comment]
Yeah, this is already made aware of, by me, several times...

I'm sure they are trying to fix this...

**Comment by ghost** [comment]
where is duplicate?

**Comment by Drflash55** [comment]
There is not an issue on here, but I said it on the gitter.im chat.

@ErmiyaEskandary Does that count?

**Comment by ghost** [comment]
oh ok but at least there is an issue here

**Comment by ermiyaeskandary** [comment]
@Drflash55 We need to make issues here . But thanks anyway. We are working on this surely...

**Comment by Seple** [comment]
I reported the similar problem + photo #116

**Comment by Evanito** [comment]
@Drflash55 Since Issues are our official means of workflow management, it is only a duplicate if there is another issue for the same topic.

**Comment by ChadSki** [comment]
Fixed by [pull #143](https://github.com/ErmiyaEskandary/Slither.io-bot/pull/143)?

**Comment by Drflash55** [comment]
Someone test out to see if [pull #143](https://github.com/ErmiyaEskandary/Slither.io-bot/pull/143) fixes the issue of the bot trying to go after food behind snakes...

**Comment by tjorim** [comment]
No it seems as like it isn't fixed, checking if a path towards food is
clear has not been implemented yet.

**Comment by ermiyaeskandary** [comment]
@OneEyed Done with the latest grid method implementation?

**Comment by ermiyaeskandary** [comment]
Not evident for me - if confirmed **with the latest version** please reopen...
