### ISSUE TITLE
Version 0.9.6 is too resource intensive

### ISSUE THREAD

**Issue by dingyang1988** [ermiyaeskandary/Slither.io-bot#196]
I am running the bot on Google Chrome Version 50.0.2661.102 m with Tampermonkey.

Starting from version 0.9.6, I notice that the bot has become very resource intensive. Even when running in mobile rendering mode, I suffer a major drop in FPS when in situations with a few bigger snakes on the screen. 

With the bot disabled, I'm getting FPS of around 50. Once the bot is enabled, the FPS dropped immediately to around 20 only, which often resulted in death of the snake due to the lag.

My computer was able to run 3 instances of bots in 3 separate windows at the same time without much issue when using version 0.9.3, but now it's struggling to even run one at version 0.9.6.

I understand that with the addition of new features, the code is bound to get more complicated and as a result more resource intensive. But I think this is a little too much that it's now affecting the performance of the bot.

I have downgraded back to v0.9.3 and it's running fine, so I suppose this rules out the server as the reason for the lag.

**Comment by ermiyaeskandary** [comment]
Can you test the latest version ?

**Comment by dingyang1988** [comment]
Testing it out now. Will update soon.
By the way, I think I may have found out the reason that causes the bug in #177, and posted a video demonstrating the bug.

**Comment by dingyang1988** [comment]
Hi, is the latest version renamed to Slither.io-bot A*, version 0.9.3?
I cant enable the bot in this latest version, debugging console showing this error message: 
`VM220:445 Uncaught ReferenceError: collisionGrid is not defined`

**Comment by ermiyaeskandary** [comment]
Are you sure ? Works here for me

**Comment by ermiyaeskandary** [comment]
Disable other scripts please...

**Comment by OthorWight** [comment]
This is the only script i have installed. I am getting the same error when trying to enable the bot.
Here is a section of the errors.
VM86:445 Uncaught ReferenceError: collisionGrid is not defined
VM86:30 Stopping Bot.
VM86:718 Grid debugging set to: true
VM86:718 Grid debugging set to: false
VM86:718 Grid debugging set to: true
VM86:718 Grid debugging set to: false
VM86:30 Starting Bot.
VM86:445 Uncaught ReferenceError: collisionGrid is not defined
VM86:30 Stopping Bot.
VM86:30 Starting Bot.
VM86:445 Uncaught ReferenceError: collisionGrid is not defined
VM86:30 Stopping Bot.
VM86:30 Starting Bot.
VM86:445 Uncaught ReferenceError: collisionGrid is not defined
VM86:30 Stopping Bot.
VM86:30 Starting Bot.
VM86:445 Uncaught ReferenceError: collisionGrid is not defined
VM86:30 Stopping Bot.
VM86:30 Starting Bot.
VM86:445 Uncaught ReferenceError: collisionGrid is not defined
VM86:30 Stopping Bot.
VM86:30 Starting Bot.
VM86:445 Uncaught ReferenceError: collisionGrid is not defined
VM86:30 Stopping Bot.
VM86:30 Starting Bot.
VM86:445 Uncaught ReferenceError: collisionGrid is not defined
VM86:30 Stopping Bot.

**Comment by Salvationdk** [comment]
Dosnt work here either..

**Comment by Salvationdk** [comment]
> VM2813:4 ERROR: Execution of script 'Slither.io-bot A*' failed! collisionGrid is not definedwindow.scores @ VM2813:4(anonymous function) @ VM2813:5(anonymous function) @ VM2703:2u @ VM2767:52(anonymous function) @ VM2812:1(anonymous function) @ VM2703:2b @ VM2703:1ha @ VM2767:54F @ VM2767:52Pa.create @ VM2767:61z @ VM2767:13
> VM2813:4 ReferenceError: collisionGrid is not defined
>     at Object.bot.launchBot (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:445:17)
>     at eval (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:1014:9)
>     at Object.eval (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:1016:3)
>     at <anonymous>:2:95
>     at window.scores (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:4:1)
>     at Object.eval (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:5:3)
>     at <anonymous>:2:95
>     at u (eval at <anonymous> (unknown source), <anonymous>:52:323)
>     at eval (eval at <anonymous> (unknown source), <anonymous>:1:24)
>     at <anonymous>:2:95
> VM2813:30 Stopping Bot.

**Comment by hnphi** [comment]
i can't start bots. When i press "T" then console log show this:
`VM46071:445 Uncaught ReferenceError: collisionGrid is not defined`

**Comment by ermiyaeskandary** [comment]
Ah - found the issue.

**Comment by ermiyaeskandary** [comment]
Can you test now with the latest version ? Should be fixed

**Comment by dingyang1988** [comment]
Still seeing the same error message. Is installation of the bot still the same? Just using bot.user.js? Or do I have to install the other files as well?

**Comment by ermiyaeskandary** [comment]
**bot.meta.user.js**

**Comment by dingyang1988** [comment]
Doesn't work. 
I think the bot isn't even loaded.

All I get is this in the console. 

> VM8332:53Syntax error @ "Slither.io-bot A*"!
> ##########################
> JSHINT output:
> require: (E030) Expected an identifier and instead saw '<' on line: 6 at character: 1
> require: (E033) Expected an operator and instead saw '!' on line: 6 at character: 2
> require: (W030) Expected an assignment or function call and instead saw an expression on line: 6 at character: 2
> require: (W033) Missing semicolon on line: 6 at character: 3
> require: (W030) Expected an assignment or function call and instead saw an expression on line: 6 at character: 3
> require: (W033) Missing semicolon on line: 6 at character: 10
> require: (E030) Expected an identifier and instead saw '<' on line: 7 at character: 1
> require: (E041) Unrecoverable syntax error. (0% scanned) on line: 7 at character: 2
> ##########################
> 
> SyntaxError: Unexpected token <
>     at v (eval at <anonymous> (unknown source), <anonymous>:52:428)
>     at eval (eval at <anonymous> (unknown source), <anonymous>:1:24)
>     at <anonymous>:2:95
>     at b (<anonymous>:1:200)
>     at ha (eval at <anonymous> (unknown source), <anonymous>:54:243)
>     at C (eval at <anonymous> (unknown source), <anonymous>:52:495)
>     at Object.Pa.create (eval at <anonymous> (unknown source), <anonymous>:61:313)
>     at x (eval at <anonymous> (unknown source), <anonymous>:13:184)(anonymous function) @ VM8332:53(anonymous function) @ VM8332:22e.Message.E @ VM8294:7(anonymous function) @ VM8294:8e @ content.js:6(anonymous function) @ content.js:7sendResponseAndClearCallback @ extensions::messaging:342messageListener @ extensions::messaging:373target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:387target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94EventImpl.dispatch_ @ extensions::event_bindings:371EventImpl.dispatch @ extensions::event_bindings:393target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94dispatchOnMessage @ extensions::messaging:320
> VM8332:52 Uncaught SyntaxError: Unexpected token <

I don't even see the bot HUD at all.

**Comment by ermiyaeskandary** [comment]
Can you test now with the latest version ?

**Comment by ermiyaeskandary** [comment]
Confirmed working.

**Comment by ermiyaeskandary** [comment]
What about lag and performance ?

**Comment by dingyang1988** [comment]
Bot works now. Will report back on performance soon.

**Comment by dingyang1988** [comment]
Wow! The current version is freaking awesome! I'm mightily impressed! I'm gaining mass very fast. 

Performance wise, I think it's better now. The FPS took quite a hit when grid debugging is enabled, but when disabled it's quite ok.

So from now on all installation with be done with bot.meta.user.js? What's the difference between these files?

**Comment by dingyang1988** [comment]
But seems to be crashing into sides of snakes quite often, even when not accelerating. Hmm...

**Comment by dingyang1988** [comment]
FPS drops quite a bit when the scene gets a little busy.. When bot is disabled in that scene, FPS stays at 40+, but dropped to around high 20s to low 30s when bot is enabled.

But compared to previous version of bots with just primitive functions, I think I can live with that... :smile: 

Kudos to the developer team!

**Comment by joetex** [comment]
There are many settings (performance and smartness) that will be configurable in the near future.  The different systems that run the bot are all new, so it took a bit of time to get them to a stable state.  Now that we can implement new behaviors easily, we should be able to bring a smarter bot much quicker.

**Comment by ermiyaeskandary** [comment]
We also are just using bot.meta.user.js - hot loads files and it is the file to install. :+1:
Kudos to the community ! :)

**Comment by ermiyaeskandary** [comment]
Should be fixed now as we have changed systems... Feedback ?

**Comment by dingyang1988** [comment]
I guess we can consider this case closed?
